### ISSUE TITLE
Add error message for maxWarnings

### ISSUE THREAD

**Issue by dapicester** [lwhiteley/eslint-output#10]
I noticed that if we run with `maxWarnings` set, the command fails but there is no visible message to the user.

For example, I define a script in `package.json`:
```json
"scripts":{
  "lint": "eslint-output --maxWarnings 150"
}
```
The output looks like this:
<img width="762" alt="Screen Shot 2021-02-23 at 11 55 44" src="https://user-images.githubusercontent.com/3007132/108800432-115dba00-75ce-11eb-96ba-e4906f09843f.png">

As you see, it is not clear for the user why the `lint` script failed. Is it possible to print an error message?

**Comment by lwhiteley** [comment]
should now be resolved with v3.0.1
