### ISSUE TITLE
Release a new version to npmjs

### ISSUE THREAD

**Issue by eugenrein-scout24** [lwhiteley/eslint-output#12]
We received a security issue from Dependabot related to y18n:

> The npm package y18n before versions 3.2.2, 4.0.1, and 5.0.5 is vulnerable to Prototype Pollution.

I just saw that Dependabot automatically updated y18n in the repo to 4.0.1. Could you please also release a new version to npmjs?

**Comment by lwhiteley** [comment]
version 2.0.4 released to npm
