### ISSUE TITLE
eslint-output succeeds if there are warnings

### ISSUE THREAD

**Issue by gperrow** [lwhiteley/eslint-output#4]
If I run "eslint-output --max-warnings 0 myfile.js" and there are warnings but no errors, the return code is 0 indicating success.

**Comment by lwhiteley** [comment]
unfortunately, the limitation here is that I have not seen a good way to forward the cli options to eslint in this manner. 

however it is simple to mimic this feature, ill create a PR to add it

**Comment by lwhiteley** [comment]
version `1.2.0` released

you can now do 

`eslint-output --max-warnings=0`

**Comment by gperrow** [comment]
Works perfectly. Thanks for the quick fix
